
Date: 11/05/2018

Version: 1.0

Environment: Python 3 and Jupyter notebook

Libraries used: please include the main libraries you used in your assignment here, e.g.,:
* pandas (for dataframe, included in Anaconda Python 2.7) 
* re (for regular expression, included in Anaconda Python 2.7) 
* numpy (for numpy array, included in Anaconda Python 2.7) 
* sklearn (for linear regression)

## 1.  Import libraries

In [26]:
import pandas as pd

## 2. Parse File

In [27]:
dataset1 = pd.read_csv('dataset1_solution.csv')
dataset2 = pd.read_csv('dataset2_integration.csv')
#dataset1.drop(columns = ['Unnamed: 0'], inplace = True)
# reorder columns in dataset2 as dataset1
# dataset2.columns = ['Id', 'SourceName','Title','Location','ContractType', 'ContractTime','Company', 'Category', 'SalaryPerAnnum','OpenDate','CloseDate']
dataset2 = dataset2[list(dataset1.columns)]

In [3]:
dataset1.Category.value_counts()

35004    1011
30000     892
39996     849
45000     752
32496     744
37500     707
24996     690
50004     616
27504     582
42504     549
24000     448
54996     448
20004     399
22500     387
47496     364
60000     321
18000     316
21996     296
21000     287
26004     286
18996     283
27996     278
52500     275
27000     260
29004     256
23004     247
17004     244
28500     219
23496     207
26496     206
         ...
67800       1
11100       1
35592       1
19104       1
19056       1
43596       1
19008       1
10812       1
51744       1
18864       1
10620       1
41325       1
26964       1
75996       1
67752       1
26052       1
26772       1
18384       1
34728       1
34536       1
26340       1
34488       1
26292       1
18096       1
9852        1
26196       1
17952       1
34296       1
26100       1
16392       1
Name: Category, Length: 1565, dtype: int64

In [4]:
# observation for different information
dataset2.Category.value_counts()

IT Jobs                             6854
Engineering Jobs                    4199
Healthcare & Nursing Jobs           3984
Finance & Accounting Jobs           2842
Hospitality & Catering Jobs         2310
Sales Jobs                          2268
Teaching Jobs                       1890
PR, Advertising & Marketing Jobs     929
Name: Category, dtype: int64

In [5]:
# fit data format in both dataset1 and dataset2
dataset2.Category.replace('Finance & Accounting Jobs', 'Accounting & Finance Jobs', inplace = True)

In [6]:
# change the monthly salary to annually
dataset2.SalaryPerAnnum = dataset2.SalaryPerAnnum*12

### a. ContractTime

In [7]:
dataset1.ContractTime.value_counts(dropna= False)

NaN                                    3835
UKStaffsearch                           248
CVbrowser                               170
Randstad                                169
JOBG8                                   159
Matchtech Group plc.                    150
Chef Results                            137
Penguin Recruitment                     134
Hays                                    115
London4Jobs                             112
COREcruitment International             111
JAM Recruitment Ltd                     109
Computer People                          99
Clear Selection                          92
Monarch Recruitment                      89
Towngate Personnel                       79
Cherryred Recruitment                    69
Senitor Associates                       67
Support Services Group                   62
Capita Resourcing                        62
Modis                                    62
Aspire Data Recruitment                  61
Adecco                                   57
Populus Healthcare                       55
Idex Consulting                          55
Evolution Recruitment Solutions          55
Swiis Healthcare                         54
Bee Recruitment London Ltd               53
IC Software                              52
The Placement Group                      52
                                       ...
Solutions2Recruitment                     1
Tenet Group Limited                       1
Synergize Consulting Limited              1
Auctus Outsource                          1
Headline   Cambridge                      1
CRM Limited                               1
1st Step Solutions Ltd                    1
F5 IT Recruitment Ltd                     1
Paribus Global Ltd                        1
Elizabeth Hunt Recruitment                1
MONTASH ASSOCIATES                        1
Guru Careers                              1
SELECTIVE RECRUITMENT LIMITED             1
PSD Technology Contracts Ltd.             1
Air Energi                                1
RBW Consulting Solutions Ltd              1
Key People Limited                        1
Frankland Associates                      1
Metaskil                                  1
IRON MOUNTAIN  LTD                        1
Recruit12                                 1
Talk Staff Recruitment                    1
Parc Ellis Solutions Ltd                  1
People for Work                           1
Brightred Resourcing Limited              1
Teamwork Technical Services Limited       1
Mars Recruitment                          1
New Line SR Ltd                           1
Way Ahead Care                            1
Ifftner Solutions                         1
Name: ContractTime, Length: 4880, dtype: int64

In [8]:
# impute the missing value and inconsistence
dataset2.ContractTime.value_counts(dropna= False)

perm.     16505
NaN        5513
contr.     3258
Name: ContractTime, dtype: int64

In [9]:
# fit data format in both dataset1 and dataset2
dataset2.ContractTime.replace(['perm.', 'contr.'], ['permanent', 'contract'], inplace = True)
dataset2.ContractTime.fillna('non-specificed', inplace = True)

### b.  ContractType

In [10]:
dataset1.ContractType.value_counts()

permanent        16194
non-specified     6212
contract          2671
Name: ContractType, dtype: int64

In [11]:
dataset2.ContractType.value_counts(dropna= False)

NaN    20457
ft      4353
pt       466
Name: ContractType, dtype: int64

In [12]:
# fit data format in both dataset1 and dataset2
dataset2.ContractType.replace(['ft','pt'], ['full-time','part-time'], inplace = True)
dataset2.ContractType.fillna('non-specified', inplace = True)

In [13]:
# dataset2.Category.value_counts()

In [14]:
# dataset2.info()

### c. Company Missing Value

##### Didn‘t impute dataset2 due to dataset1

In [15]:
# dataset2.Company[dataset2['Category']== "IT Jobs"].value_counts(dropna = False)
# dataset2.Company[dataset2['Category']== "Healthcare & Nursing Jobs"].value_counts(dropna = False)
# dataset2.Company[dataset2['Category']== "Engineering Jobs"].value_counts(dropna = False)
# dataset2.Company[dataset2['Category']== "Accounting & Finance Jobs"].value_counts(dropna = False)
# dataset2.Company[dataset2['Category']== "Sales Jobs"].value_counts(dropna = False)
# dataset2.Company[dataset2['Category']== "Hospitality & Catering Jobs"].value_counts(dropna = False)
# dataset2.Company[dataset2['Category']== "Teaching Jobs"].value_counts(dropna = False)
# dataset2.Company[dataset2['Category']== "PR, Advertising & Marketing Jobs"].value_counts(dropna = False)

In [16]:
# dataset2.Company[dataset2['Category']== "IT Jobs"] = dataset2.Company[dataset2['Category']== "IT Jobs"].fillna(value='Senitor Associates')
# dataset2.Company[dataset2['Category']== "Healthcare & Nursing Jobs"] = dataset2.Company[dataset2['Category']== "Healthcare & Nursing Jobs"].fillna(value='Populus Healthcare')
# dataset2.Company[dataset2['Category']== "Engineering Jobs"] = dataset2.Company[dataset2['Category']== "Engineering Jobs"].fillna(value='Randstad')
# dataset2.Company[dataset2['Category']== "Accounting & Finance Jobs"] = dataset2.Company[dataset2['Category']== "Accounting & Finance Jobs"].fillna(value='Michael Page Finance')
# dataset2.Company[dataset2['Category']== "Sales Jobs"] = dataset2.Company[dataset2['Category']== "Sales Jobs"].fillna(value='Moriati Media UK Ltd')
# dataset2.Company[dataset2['Category']== "Hospitality & Catering Jobs"] = dataset2.Company[dataset2['Category']== "Hospitality & Catering Jobs"].fillna(value='COREcruitment International')
# dataset2.Company[dataset2['Category']== "Teaching Jobs"] = dataset2.Company[dataset2['Category']== "Teaching Jobs"].fillna(value='Capita Education')
# dataset2.Company[dataset2['Category']== "PR, Advertising & Marketing Jobs"] = dataset2.Company[dataset2['Category']== "PR, Advertising & Marketing Jobs"].fillna(value='Michael Page Marketing')

### d. Data Intergration

In [17]:
frames = [dataset1, dataset2]
result = pd.concat(frames)

In [24]:
result

,SourceName,Title,Location,ContractType,ContractTime,Company,Category,SalaryPerAnnum,OpenDate,CloseDate
Id,,,,,,,,,,
12612628,Engineering Systems Analyst,Dorking,non-specified,permanent,Gregory Martin International,Engineering Jobs,24996,cv-library.co.uk,2012-11-03 00:00:00,2012-12-03 00:00:00
12612830,Stress Engineer Glasgow,Glasgow,non-specified,permanent,Gregory Martin International,Engineering Jobs,30000,cv-library.co.uk,2013-01-08 15:00:00,2013-04-08 15:00:00
12612844,Modelling and simulation analyst,Hampshire,non-specified,permanent,Gregory Martin International,Engineering Jobs,30000,cv-library.co.uk,2013-07-26 15:00:00,2013-09-24 15:00:00
12613049,Engineering Systems Analyst / Mathematical Mod...,Surrey,non-specified,permanent,Gregory Martin International,Engineering Jobs,27504,cv-library.co.uk,2012-12-14 00:00:00,2013-03-14 00:00:00
12613647,"Pioneer, Miser Engineering Systems Analyst",Surrey,non-specified,permanent,Gregory Martin International,Engineering Jobs,24996,cv-library.co.uk,2013-10-25 00:00:00,2013-12-24 00:00:00
19047429,Trainee Mortgage Advisor East Midlands,East Midlands,non-specified,permanent,Brite Recruitment,Accounting & Finance Jobs,21000,cv-library.co.uk,2012-07-24 00:00:00,2012-09-22 00:00:00
20199757,"PROJECT ENGINEER, PHARMACEUTICAL",Witney,non-specified,permanent,MatchBox Recruiting Ltd,Healthcare & Nursing Jobs,37500,cv-library.co.uk,2013-03-28 12:00:00,2013-04-27 12:00:00
20797143,Chef de Partie Award Winning Restaurant Exce...,Derby,non-specified,non-specified,Chef Results,Hospitality & Catering Jobs,15996,caterer.com,2013-10-27 00:00:00,2013-12-26 00:00:00
22579462,Quality Engineer,Gateshead,non-specified,permanent,Asset Appointments,Engineering Jobs,21996,cv-library.co.uk,2013-08-15 00:00:00,2013-09-14 00:00:00
22933091,Chef de Partie Award Winning Dining Live In ...,UK,non-specified,non-specified,Chef Results,Hospitality & Catering Jobs,18000,caterer.com,2012-08-14 00:00:00,2012-08-28 00:00:00
23528672,Senior Fatigue and Damage Tolerance Engineer,Avon,non-specified,permanent,Gregory Martin International,Engineering Jobs,39504,cv-library.co.uk,2013-10-19 12:00:00,2013-11-18 12:00:00
23529949,C I Design Engineer,Wolverhampton,non-specified,permanent,Rullion Engineering Ltd,Engineering Jobs,33504,cv-library.co.uk,2012-12-11 12:00:00,2013-01-10 12:00:00
23530231,Lead Engineers (Stress),UK,non-specified,permanent,Gregory Martin International,Engineering Jobs,39504,cv-library.co.uk,2012-11-13 12:00:00,2013-02-11 12:00:00
24104334,"Relief Chef de Partie Croydon, Surrey Live in",UK,non-specified,non-specified,Towngate Personnel,Hospitality & Catering Jobs,17280,caterer.com,2013-10-29 00:00:00,2013-11-28 00:00:00
24835524,Senior Control and Instrumentation Engineer,Berkshire,non-specified,permanent,Gregory Martin International,Engineering Jobs,41496,cv-library.co.uk,2012-12-14 00:00:00,2013-01-13 00:00:00
24835548,Control and Instrumentation Engineer,Berkshire,non-specified,permanent,Gregory Martin International,Engineering Jobs,31500,cv-library.co.uk,2012-07-09 12:00:00,2012-08-08 12:00:00
24854800,Electrical / ICA Engineer,Surrey,non-specified,permanent,Gregory Martin International,Engineering Jobs,32496,cv-library.co.uk,2013-02-05 00:00:00,2013-03-07 00:00:00
25337172,Pastry Chef for **** red star **** rosette hot...,North East England,non-specified,non-specified,Clear Selection,Hospitality & Catering Jobs,24000,caterer.com,2013-06-10 00:00:00,2013-08-09 00:00:00
25452606,CHEF DE PARTIE POSITION IN **** ROSETTE HOTEL ...,North Yorkshire,non-specified,non-specified,Clear Selection,Hospitality & Catering Jobs,15996,caterer.com,2013-08-25 00:00:00,2013-09-24 00:00:00
25452680,"Senior Sous Chef for **** rosette kitchen, up ...",North East England,non-specified,non-specified,Clear Selection,Hospitality & Catering Jobs,26004,caterer.com,2012-01-01 12:00:00,2012-01-15 12:00:00
25556432,"General Manager Funky, Cool Restaurant Concep...",East Sheen,non-specified,non-specified,Bee Recruitment London Ltd,Hospitality & Catering Jobs,31500,caterer.com,2013-09-26 12:00:00,2013-10-26 12:00:00
25892031,MICE Sales and Marketing Manager,Buckinghamshire,non-specified,non-specified,Chess Partnership,Hospitality & Catering Jobs,30000,caterer.com,2012-08-25 12:00:00,2012-10-24 12:00:00
27527047,C/C++ Developer,London,non-specified,permanent,Indigo 21 Ltd,IT Jobs,32496,cv-library.co.uk,2012-05-19 15:00:00,2012-06-18 15:00:00
27527050,Senior PHP Developer,Central London,non-specified,permanent,Indigo 21 Ltd,IT Jobs,45000,cv-library.co.uk,2012-06-23 15:00:00,2012-08-22 15:00:00
27527063,Senior Website Designer,York,non-specified,permanent,Indigo 21 Ltd,IT Jobs,24996,cv-library.co.uk,2013-08-10 00:00:00,2013-09-09 00:00:00
27527077,Business Development Manager,Newcastle Upon Tyne,non-specified,permanent,Asset Appointments,IT Jobs,21000,cv-library.co.uk,2012-02-28 15:00:00,2012-04-28 15:00:00
27739522,Welwyn Chef de Partie does it get any better t...,UK,non-specified,non-specified,Clear Selection,Hospitality & Catering Jobs,18000,caterer.com,2013-01-06 12:00:00,2013-03-07 12:00:00
27740574,Pastry Chef AL**** ****AA Rosette Restaurant,UK,non-specified,non-specified,Clear Selection,Hospitality & Catering Jobs,18996,caterer.com,2012-03-20 12:00:00,2012-04-03 12:00:00
27754996,QA Engineer,Cambridge,non-specified,permanent,Indigo 21 Ltd,IT Jobs,30000,cv-library.co.uk,2013-05-31 15:00:00,2013-07-30 15:00:00
28059808,Documentation Engineer,Manchester,non-specified,contract,Rullion Engineering Ltd,Engineering Jobs,48000,cv-library.co.uk,2013-08-18 12:00:00,2013-09-17 12:00:00
...,...,...,...,...,...,...,...,...,...,...
72697232,justengineers.net,CAD Technician Civil ****D,Nottingham,non-specified,permanent,Hays Specialist Recruit Ltd Construction,Engineering Jobs,24996,2012-04-03 00:00:00,2012-05-03 00:00:00
72697249,justengineers.net,Ecology Consultant,Cambridge,non-specified,permanent,Fusion People Ltd,Engineering Jobs,26496,2012-03-20 00:00:00,2012-05-19 00:00:00
72697286,justengineers.net,Training Delivery Instructor,UK,non-specified,permanent,Minstrell Recruitment LTD,Engineering Jobs,24996,2013-12-19 00:00:00,2014-03-19 00:00:00
72697289,justengineers.net,Energy Sales Manager,Blackpool,non-specified,permanent,Morgan Hunt UK Limited,Engineering Jobs,22500,2013-05-16 15:00:00,2013-08-14 15:00:00
72697334,justengineers.net,Experienced Tree Surgeon,Poole,non-specified,permanent,R S S Limited,Engineering Jobs,16080,2013-10-01 15:00:00,2013-12-30 15:00:00
72697363,justengineers.net,Mechanical / Electrical Fitter,Wiltshire,non-specified,permanent,Resourcing Solutions Ltd,Engineering Jobs,11496,2013-02-21 15:00:00,2013-04-22 15:00:00
72697506,justengineers.net,Warranty Engineer,UK,non-specified,contract,Resourcing Solutions Ltd,Engineering Jobs,24000,2013-09-09 00:00:00,2013-09-23 00:00:00
72701954,hays.co.uk,Cad TechnicianCivil,Derbyshire,non-specified,contract,NaN,Engineering Jobs,31680,2013-12-26 12:00:00,2014-01-09 12:00:00
72702355,hays.co.uk,Senior Operations Manager PPI,Middlesbrough,non-specified,contract,NaN,Accounting & Finance Jobs,96000,2013-07-03 12:00:00,2013-09-01 12:00:00
72702599,jobsinsocialwork.co.uk,Scientific Editorial Team Leader,London,full-time,permanent,Executive Facilities,Healthcare & Nursing Jobs,50004,2013-06-26 15:00:00,2013-09-24 15:00:00
72702787,emedcareers.com,Healthcare Development Manager,UK,non-specified,permanent,Barrington James Ltd,Healthcare & Nursing Jobs,54996,2013-04-07 12:00:00,2013-06-06 12:00:00
72702792,emedcareers.com,Senior Medical Writers: Step up to Team Leader...,London,non-specified,permanent,NonStop Recruitment,Healthcare & Nursing Jobs,54996,2013-08-11 15:00:00,2013-09-10 15:00:00
72702793,emedcareers.com,Medical Affairs Clinical Research Physician J...,UK,non-specified,permanent,Flame Pharma,Healthcare & Nursing Jobs,54996,2012-08-05 00:00:00,2012-10-04 00:00:00
72702812,emedcareers.com,Clinical Sales Specialist,UK,non-specified,permanent,New Chapter Consulting,Healthcare & Nursing Jobs,45000,2012-07-29 12:00:00,2012-10-27 12:00:00
72702814,emedcareers.com,Medical Devices Regulatory Affairs Manager Jo...,London,non-specified,permanent,Flame Pharma,Healthcare & Nursing Jobs,45000,2013-07-03 12:00:00,2013-10-01 12:00:00
72702823,emedcareers.com,SAS Programmer All Levels Permanent,UK,non-specified,permanent,Skills Alliance Limited,Healthcare & Nursing Jobs,39996,2013-03-11 15:00:00,2013-05-10 15:00:00
72702825,emedcareers.com,Pharmaceutical Analytical Team Leader Jobs in...,Northern Ireland,non-specified,permanent,Flame Pharma,Healthcare & Nursing Jobs,42504,2013-05-18 15:00:00,2013-07-17 15:00:00
72702831,emedcareers.com,Senior Quality Auditor GCP,South East England,non-specified,permanent,Real,Healthcare & Nursing Jobs,45504,2012-03-06 00:00:00,2012-05-05 00:00:00
72702839,emedcareers.com,Territory Sales Manager: South Midlands / Card...,UK,non-specified,permanent,BWB Associates trading as BW Penman,Healthcare & Nursing Jobs,41496,2012-10-26 15:00:00,2012-12-25 15:00:00
72702840,emedcareers.com,Clinical Product Specialist: South Midlands / ...,East Midlands,non-specified,permanent,BWB Associates trading as BW Penman,Healthcare & Nursing Jobs,41496,2012-11-28 00:00:00,2013-02-26 00:00:00
72702868,emedcareers.com,Senior Med Info Officer,Essex,non-specified,permanent,Key People Limited,Healthcare & Nursing Jobs,33996,2012-07-16 15:00:00,2012-09-14 15:00:00
72702870,emedcareers.com,Territory Manager Orthopaedics,UK,non-specified,permanent,Ortho Executive Limited,Healthcare & Nursing Jobs,39996,2012-01-06 15:00:00,2012-04-05 15:00:00
72702883,emedcareers.com,Territory Manager North West,UK,non-specified,permanent,Remtec Search and Selection,Healthcare & Nursing Jobs,36000,2013-05-13 00:00:00,2013-07-12 00:00:00
72702927,emedcareers.com,Senior Clinical Research Associate (SCRA) UK,UK,non-specified,permanent,Barrington James Ltd,Healthcare & Nursing Jobs,30504,2012-11-04 12:00:00,2012-12-04 12:00:00
72702933,emedcareers.com,IT Infrastructure Specialist (Mlnlycke Health ...,UK,non-specified,permanent,Molnlycke,Healthcare & Nursing Jobs,28500,2013-07-31 15:00:00,2013-10-29 15:00:00
72702956,emedcareers.com,Pharmaceutical Analytical Chemist Jobs in Nor...,Northern Ireland,non-specified,permanent,Flame Pharma,Healthcare & Nursing Jobs,23004,2013-09-24 15:00:00,2013-10-24 15:00:00
72702963,emedcareers.com,Medical Sales Representative South East Essex,UK,non-specified,contract,The Vacancy Management Company,Healthcare & Nursing Jobs,22500,2012-05-21 12:00:00,2012-06-20 12:00:00
72703193,eventjobsearch.co.uk,SENIOR PROJECT MANAGER EVENT & EXHIBITION AGENCY,Hertfordshire,full-time,permanent,Live Recruitment,"PR, Advertising & Marketing Jobs",32496,2013-11-17 15:00:00,2013-12-17 15:00:00
72705197,hays.co.uk,Curriculum Leader Mathematics,Wrexham,non-specified,permanent,NaN,Teaching Jobs,5004,2012-01-15 12:00:00,2012-03-15 12:00:00
72705203,hays.co.uk,TEACHER OF BUSINESS STUDIES AND LAW,Salisbury,non-specified,contract,NaN,Teaching Jobs,22800,2013-04-27 15:00:00,2013-05-11 15:00:00

### e. Drop duplicates

In [19]:
# use 'Title' and 'ContractTime'as a global key
# result[result.duplicated(['Title', 'ContractTime'])]
# result.drop_duplicates(['Title', 'ContractTime'], inplace = True)

## 3. Output

In [20]:
# set ID as index of dataframe
result.set_index(['Id'], inplace = True)

In [21]:
# result.to_csv("C:/Users/XiaoFan/Desktop/5196 wrangling/dataset1_dataset2_solution.csv", encoding='utf-8')